#!/bin/bash

export LOG_LEVEL=debug

for file in ./tests/*.py
do
    echo $file
    exec nosetests $file \
        --logging-format='%(asctime)s [%(name)s] %(levelname)-6s %(message)s' \
        --with-coverage \
        --cover-package=tormysql
done
